flatten out testing logic to make tests more readable
temporalio/temporal-pendulum pull request #18
Opened 2022-07-11 02:17 UTC by vkarpov15

## What was changed

Current code uses `runUntil()`, [which makes it a bit tricky to test queries and signals](https://github.com/temporalio/documentation/pull/1252). It could also benefit from using Jest hooks rather than helper functions.

Also, why are we using Jest here? I'm a bit wary of recommending users use Jest.

## Why?

I haven't been able to repro https://github.com/temporalio/sdk-typescript/issues/728, but I suspect that `runUntil()` may have something to do with it. @joebowbeer can you try out these tests and see if you're still experiencing the issue you reported in https://github.com/temporalio/sdk-typescript/issues/728 ?

## Checklist

1. Closes 

2. How was this tested:

3. Any docs updates needed?

2022-07-11 04:56 UTC, joebowbeer requested changes
Thanks! The few changes suggested are hoisting the gameInfo _seed_ value.

Also: Why does each test leave its workflow dangling until the final afterAll? That seems unclean.

Previously, every test sent an exit signal and awaited a result. Perhaps that functionality can be moved into `afterEach`. (Then the exit-signal test can be an empty test.)

2022-07-11 04:56 UTC, joebowbeer commented on position-node/src/workflows.test.ts
> +const taskQueue = 'test';
```suggestion
const taskQueue = 'test';
const initInfo = gameInfo({ anchorX: 1 });
```

2022-07-11 04:56 UTC, joebowbeer commented on position-node/src/workflows.test.ts
> +    args: [gameInfo({ anchorX: 1 })],
```suggestion
    args: [initInfo],
```

2022-07-11 04:56 UTC, joebowbeer commented on position-node/src/workflows.test.ts
>    const info = gameInfo({ anchorX: 1 });
```suggestion
```

@vkarpov15 I like the refactor. It suits these tests well.

The one thing I don't like is that this info value is created out of thin air here. I think this should be hoisted to a constant `initInfo` where it can be used in `beforeEach` as a seed and then again in this test as an expected value.

2022-07-11 04:56 UTC, joebowbeer commented on position-node/src/workflows.test.ts
> +  expect(queryResult).toEqual(info);
```suggestion
  expect(queryResult).toEqual(initInfo);
```

2022-07-12 15:06 UTC, vkarpov15 commented
@joebowbeer take a look at these latest changes, I just removed the `gameInfo()` function in favor of using the spread operator. I also added a `afterEach()` that terminates the Workflow handle to clean up Workflow handles.

I disagree with your assessment of Jest. In my experience, Jest should only be considered by expert architects with decades of JavaScript experience, because of the difficulty with configuring Jest and managing compatibility issues. The advantage of Mocha is that your code runs in plain old Node.js, whereas Jest replaces `require()`, `Date()`, and numerous other globals with their own implementations that are frequently incompatible with Node's. Jest isn't a testing framework, it's a whole separate JavaScript runtime. That's just my thoughts though, I don't speak for Temporal.

I'd be curious to hear from @bergundy and @lorensr about whether we should use Jest, Mocha, Ava, or something else as the "default" testing framework in our examples.

2022-07-12 15:12 UTC, bergundy commented
As users have pointed out, jest is by far the most popular testing framework for JS.
It's quite tricky to make the SDK work well with it and we've had at least 3-4 jest related issues reported already.
Ideally testing with jest would just work but in reality it looks like it's not that simple.

2022-07-12 15:15 UTC, bergundy commented on position-node/src/workflows.test.ts
> +    // TODO: make TypeScript SDK export WorkflowNotFoundError
```
import { WorkflowNotFoundError } from '@temporalio/client';
```

2022-07-12 15:16 UTC, bergundy reviewed
I personally prefer the first approach where we start a worker per test

2022-07-12 16:26 UTC, vkarpov15 commented
@bergundy why do you prefer starting a worker per test? Not saying you're wrong - I was just under the impression that starting a worker was an expensive operation, so it would be better to only start the worker once to make tests run faster.

@joebowbeer I agree that we should support Jest as much as possible, including having samples that use Jest. I'd just prefer that we use something lighter, like Mocha or Ava, in cases where we aren't specifically explaining testing with Jest or integrating with a framework whose community mostly uses Jest. For example, the Nest sample that I'm working on uses Jest, because that's what Nest's starter uses. Although for that, I'd like to add some documentation related to best practices about testing with Jest, similar to [Mongoose's Jest docs](https://mongoosejs.com/docs/jest.html), that mentions details like needing to set `NODE_OPTIONS=--experimental-vm-modules`

2022-07-13 05:22 UTC, bergundy commented
@vkarpov15 the reason I want to use a worker per test is because you typically mock activities per test and of course need a new worker for registration.

2022-07-13 05:23 UTC, bergundy commented
Starting a worker is pretty cheap, bundling workflows OTOH isn't so that is better done once per test file.

2022-07-13 16:23 UTC, joebowbeer requested changes
Looking good!

Request to hoist the initial value.

Also consider adding comment about ignored error.

2022-07-13 16:23 UTC, joebowbeer commented on position-node/src/workflows.test.ts
> +    if (err instanceof WorkflowNotFoundError) {
I assume this is only here to accommodate the exit signal test, but as a side-effect may also hide some unexpected  behavior.

Add comment?

2022-07-13 16:23 UTC, joebowbeer commented on position-node/src/workflows.test.ts
> +  const info = { ...gameInfo, anchorX: 1 };
```suggestion
```

2022-07-13 16:23 UTC, joebowbeer commented on position-node/src/workflows.test.ts
> +  expect(queryResult).toEqual(info);
```suggestion
  expect(queryResult).toEqual(initInfo);
```

The expected value of this query is not created out of thin air; it is the initial value provided on workflow creation.

2022-07-13 16:23 UTC, joebowbeer commented on position-node/src/workflows.test.ts
> +});
```suggestion
});

const initInfo = { ...gameInfo, anchorX: 1 };
```

2022-07-13 16:23 UTC, joebowbeer commented on position-node/src/workflows.test.ts
> +    args: [{ ...gameInfo, anchorX: 1 }],
```suggestion
    args: [initInfo],
```

2022-07-13 20:22 UTC, vkarpov15 commented
@joebowbeer I addressed your comments by checking the Workflow's status using `describe()` in `afterEach()`. What do you think of that approach?

@bergundy I made it so that the tests create a bundle using `bundleWorkflowCode()` in the `before()` hook, but create a Worker in `beforeEach()`. So create a new Worker for every test, but only bundle once. What do you think of that approach?

2022-07-13 22:35 UTC, bergundy commented
Creating the worker in `beforeEach` doesn't give any value over setting it up in the `before` hook.
My point for creating the worker in each test was so the worker can be customized if necessary (apparently it's not in this case), I'd be fine with either approach but in general in our samples I'd want to push users in the worker per test direction.

Anyways, TBH I don't see that much value in this PR, I think the code was fine the way it was but it's definitely not worse, just not a good use of time IMHO.

2022-07-14 19:44 UTC, joebowbeerxealth reviewed
LGTM

2022-07-14 19:45 UTC, joebowbeer approved these changes
LGTM - but see most recent comment

2022-07-14 19:57 UTC, vkarpov15 commented
@joebowbeer I'm going to merge this PR since we have LGTMs. I think we're getting a little off track here, since this was just meant to be a quick PR to (1) potentially address https://github.com/temporalio/sdk-typescript/issues/728, (2) minimize callback-type code. I don't think us spending more time on this PR is valuable.

2022-07-14 19:57 UTC, merged